services:
  mongo:
    image: mongo:latest
    container_name: mongodb-nextjs
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  nextjs-app:
    build:
      context: ./
    container_name: nextjs-app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge